---
- name: Agregar usuario node_exporter.
  user:
    name: node_exporter
    shell: /bin/false
    system: true
    create_home: no

- name: Descargar y extraer.
  unarchive:
    src: '{{ node_exporter }}'
    dest: /tmp
    remote_src: yes

- name: Copiar binario node_exporter al /usr/local/bin
  copy: 
    src: '/tmp/{{ node_exporter_version }}/node_exporter'
    dest: /usr/local/bin/
    remote_src: yes

- name: Configurar permisos de ejecucion
  file:
    path: /usr/local/bin/
    owner: node_exporter
    group: node_exporter
    mode: u+x,g+x,o+x

- name: Crear archivo de conf de servicio node_exporter
  file:
    path: /etc/systemd/system/node_exporter.service
    state: touch
    mode: u=rw,g=rw,o=r

- name: Cargar conf de servicio node_exporter.
  template:
    src: systemd/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Systemctl reload
  systemd: 
    daemon_reload: yes

- name: Iniciar servicios node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes

- name: Agregar permisos al puerto en el firewall.
  firewalld:
    port: 9100/tcp
    permanent: yes
    state: enabled

- name: Forzar cambios en el firewall.
  systemd:
    name: firewalld
    state: reloaded
  
- name: Chequear que el puerto 9100 este disponible.
  wait_for:
    port: 9100
    state: started
    timeout: 10